# Generated by Django 2.0.5 on 2020-04-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_medG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='prix',
            field=models.CharField(max_length=120, verbose_name='Prix du médiacment'),
        ),
    ]
