# Generated by Django 2.0.5 on 2020-04-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli_medG', '0002_auto_20200417_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnetsante',
            name='addiction',
        ),
        migrations.AddField(
            model_name='addiction',
            name='carnet_sante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli_medG.CarnetSante'),
        ),
    ]
