# Generated by Django 2.0.5 on 2020-04-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=120, verbose_name='Nom francais')),
                ('name_it', models.CharField(max_length=120, verbose_name='Nom italien')),
            ],
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('mot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='italiano.Mot')),
                ('expr_fr', models.CharField(max_length=120, verbose_name='Expression francaise')),
                ('expr_it', models.CharField(max_length=120, verbose_name='Expression italienne')),
            ],
            bases=('italiano.mot',),
        ),
    ]
